#!/bin/sh

### BEGIN INIT INFO
# Provides:		pkcsslotd opencryptoki
# Required-Start:	$local_fs $remote_fs
# Required-Stop:	$local_fs $remote_fs
# Should-Start:
# Should-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	starts pkcsslotd
# Description:		pkcsslotd belongs to opencryptoki
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/pkcsslotd
NAME=pkcsslotd
DESC="PKCS#11 slot daemon"
PIDFILE=/var/lib/opencryptoki/.slotpid

test -x "$DAEMON" || exit 0

set -e

case "${1}" in
	start)
		echo -n "Starting $DESC: "
		/usr/sbin/pkcs11_startup

		start-stop-daemon --start --quiet --pidfile "$PIDFILE" --exec "$DAEMON" -- $DAEMON_OPTS
		echo "$NAME."
		;;

	stop)
		echo -n "Stopping $DESC: "
		start-stop-daemon --stop --oknodo --quiet --pidfile "$PIDFILE" --exec "$DAEMON"
		rm -f "$PIDFILE"
		echo "$NAME."
		;;

	restart|force-reload)
		"${0}" stop
		sleep 1
		"${0}" start
		;;

	status)
		if start-stop-daemon --stop --signal 0 --quiet --pidfile "$PIDFILE" --exec "$DAEMON"
		then
			echo "$NAME is running."
		else
			echo "$NAME is not running."
			exit 1
		fi
		;;

	*)
		N=/etc/init.d/$NAME
		echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
		exit 1
		;;
esac

exit 0
